ARG tag
FROM okumurareg.azurecr.io/testfront:${tag} AS build
FROM okumurareg.azurecr.io/testapi:${tag} AS base
WORKDIR /app
COPY --from=build /app/build /app/static
EXPOSE 80
ENTRYPOINT [ "uvicorn","main:app","--reload","--host","0.0.0.0","--port","8000" ]