FROM python:3.7

RUN pip install --upgrade pip fastapi uvicorn aiofiles gensim requests beautifulsoup4 lxml

WORKDIR /app

COPY ./src /app/

EXPOSE 8000
ENTRYPOINT [ "uvicorn","main:app","--reload","--host","0.0.0.0","--port","8000" ]